version: '3.8'
services:
  redis:
    container_name: rick-and-morty-api-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  rick-and-morty-api:
    container_name: rick-and-morty-api
    depends_on:
      - redis
      - db
    restart: always
    build: .
    image: dayvsonsales/rick-and-morty-api
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_RESET_TIME: 1800
volumes:
  db_data: {}
